### ISSUE TITLE
EnableExperienceModePipeline throws exception

### ISSUE THREAD

**Issue by ghost** [Vapok/Sitecore.SharedSource.DynamicSites#1]
I'm running Sitecore 8.0 rev. 150223 and as soon as I enable the .config file I get:

[NullReferenceException: Object reference not set to an instance of an object.]
Sitecore.ExperienceExplorer.Business.Pipelines.HttpRequest.EnableExperienceModePipeline.Process(HttpRequestArgs args) 374
(Object , Object[] ) 82
Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) 364
Sitecore.Nexus.Web.HttpModule.(Object , EventArgs ) 456
System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() 91
System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) 164

What's wrong?

**Comment by ghost** [comment]
custom config disables "website" and this fails: 

Sitecore.ExperienceExplorer.Business.Pipelines.HttpRequest.EnableExperienceModePipeline, Sitecore.ExperienceExplorer.Business:
NullReferenceException for SiteContext.GetSite("website").SiteInfo.Database

Site Publish:
ob started: Publish to 'web'|Items created: 0|Items deleted: 0|Items updated: 2|Items skipped: 5624|#Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentOutOfRangeException: StartIndex cannot be less than zero.
Parameter name: startIndex
   at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
   at Sitecore.Publishing.RenderingParametersCacheClearer.ClearCache(Object sender, EventArgs args)
   at Sitecore.Events.Event.EventSubscribers.RaiseEvent(String eventName, Object[] parameters, EventResult result)
   at Sitecore.Events.Event.RaiseEvent(String eventName, Object[] parameters)
   at Sitecore.Publishing.Publisher.NotifyEnd()
   at Sitecore.Publishing.Publisher.PublishWithResult()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Jobs.Job.ThreadEntry(Object state)

**Comment by Vapok** [comment]
Hi djanjicek,

So, whomever wrote the Sitecore.ExperienceExplorer.Business.Pipelines, hardcoded the site "website" into the DLL. This seems like a bug to me. Anyways.. as such, in the DynamicSites.config file, you can enable "website" and add a property to disable the hostnames, if deisred. See the update to the config file in the 1.6 commit for an example.

Sorry for the delay in responding. It's been a busy several weeks and time has been limited.

-Pete
