### ISSUE TITLE
Space in Site name causes exception

### ISSUE THREAD

**Issue by ghost** [Vapok/Sitecore.SharedSource.DynamicSites#3]
Hi Pete,

From time to time I see this kind of exception in the logs, several times actually.

ManagedPoolThread #6 14:20:02 INFO  Cache created: 'Madrid 2015[html]' (max size: 0 bytes, running total: 2405MB)
ManagedPoolThread #6 14:20:02 ERROR Error Fetching Dynamic Sites: 'cacheSizes/sites/Madrid 2015/registry' has an invalid token.
   at MS.Internal.Xml.XPath.QueryBuilder.Build(String query, Boolean allowVar, Boolean allowKey)
   at System.Xml.XPath.XPathExpression.Compile(String xpath, IXmlNamespaceResolver nsResolver)
   at System.Xml.XPath.XPathNavigator.Select(String xpath)
   at System.Xml.XmlNode.SelectSingleNode(String xpath)
   at Sitecore.Configuration.Factory.GetConfigNode(String xpath, Boolean assert)
   at Sitecore.Configuration.Factory.CreateObject(String configPath, String[] parameters, Boolean assert)
   at Sitecore.Web.SiteInfo.GetCacheSize(String attribute, StringDictionary properties, Int64 defaultSize)
   at Sitecore.Web.SiteInfo.CreateCaches(StringDictionary properties)
   at Sitecore.SharedSource.DynamicSites.Utilities.DynamicSiteManager.GetDynamicSitesDictionary(Site defaultSite)

**Comment by Vapok** [comment]
This is fixed in Version 1.7
